FROM docker.io/library/ubuntu:23.04

RUN apt update
RUN apt install -y \
    autoconf \
    automake \
    check \
    clang \
    gcc \
    libevent-dev \
    libjson-c-dev \
    libnghttp2-dev \
    libssl-dev \
    libtool \
    make \
    pkg-config \
    libpython3-dev \
    python3 \
    python3-pip \
    python3-wheel