FROM docker.io/library/ubuntu:22.10

RUN apt update
RUN apt install -y \
    autoconf \
    automake \
    check \
    gcc \
    libssl-dev \
    libtool \
    make \
    pkg-config \
    libpython3-dev \
    python3