FROM docker.io/library/alpine:3.17.3

RUN apk update
RUN apk add \
    autoconf \
    automake \
    check-dev \
    clang \
    cppcheck \
    gcc \
    json-c-dev \
    libevent-dev \
    libtool \
    make \
    musl-dev \
    nghttp2-dev \
    openssl-dev \
    pkgconfig \
    python3-dev \
    py3-pip \
    py3-wheel