FROM docker.io/library/alpine:3.16.2

RUN apk update
RUN apk add \
    autoconf \
    automake \
    check-dev \
    clang \
    gcc \
    libtool \
    make \
    musl-dev \
    openssl-dev \
    pkgconfig \
    python3-dev