FROM docker.io/library/fedora:38

RUN dnf install -y \
    autoconf \
    automake \
    check-devel \
    clang \
    cppcheck \
    gcc \
    json-c-devel \
    libevent-devel \
    libnghttp2-devel \
    libtool \
    make \
    openssl-devel \
    pkgconfig \
    python3-devel \
    python3-pip \
    python3-wheel \
    rpm-build