#include "types.h"
#include "utils.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define DNS_CHECK_TYPE(strValue, value)          \
    {                                            \
        if (strcmp(dns_type, (strValue)) == 0) { \
            result = (value);                    \
            goto finish;                         \
        }                                        \
    }

uint16_t dns_type_to_int(const char* type)
{
    int size = strlen(type) + 1;
    char* dns_type = malloc(sizeof(char) * size);
    if (dns_type == NULL) {
        perror("Cannot allocate memory");
        exit(1);
    }

    strupr(type, dns_type);

    uint16_t result = DNS_TYPE_ERROR;

    DNS_CHECK_TYPE(DNS_STR_TYPE_A, DNS_TYPE_A)
    DNS_CHECK_TYPE(DNS_STR_TYPE_NS, DNS_TYPE_NS)
    DNS_CHECK_TYPE(DNS_STR_TYPE_MD, DNS_TYPE_MD)
    DNS_CHECK_TYPE(DNS_STR_TYPE_MF, DNS_TYPE_MF)
    DNS_CHECK_TYPE(DNS_STR_TYPE_CNAME, DNS_TYPE_CNAME)
    DNS_CHECK_TYPE(DNS_STR_TYPE_SOA, DNS_TYPE_SOA)
    DNS_CHECK_TYPE(DNS_STR_TYPE_MB, DNS_TYPE_MB)
    DNS_CHECK_TYPE(DNS_STR_TYPE_MG, DNS_TYPE_MG)
    DNS_CHECK_TYPE(DNS_STR_TYPE_MR, DNS_TYPE_MR)
    DNS_CHECK_TYPE(DNS_STR_TYPE_NULL, DNS_TYPE_NULL)
    DNS_CHECK_TYPE(DNS_STR_TYPE_WKS, DNS_TYPE_WKS)
    DNS_CHECK_TYPE(DNS_STR_TYPE_PTR, DNS_TYPE_PTR)
    DNS_CHECK_TYPE(DNS_STR_TYPE_HINFO, DNS_TYPE_HINFO)
    DNS_CHECK_TYPE(DNS_STR_TYPE_MINFO, DNS_TYPE_MINFO)
    DNS_CHECK_TYPE(DNS_STR_TYPE_MX, DNS_TYPE_MX)
    DNS_CHECK_TYPE(DNS_STR_TYPE_TXT, DNS_TYPE_TXT)
    DNS_CHECK_TYPE(DNS_STR_TYPE_RP, DNS_TYPE_RP)
    DNS_CHECK_TYPE(DNS_STR_TYPE_AFSDB, DNS_TYPE_AFSDB)
    DNS_CHECK_TYPE(DNS_STR_TYPE_X25, DNS_TYPE_X25)
    DNS_CHECK_TYPE(DNS_STR_TYPE_ISDN, DNS_TYPE_ISDN)
    DNS_CHECK_TYPE(DNS_STR_TYPE_RT, DNS_TYPE_RT)
    DNS_CHECK_TYPE(DNS_STR_TYPE_NSAP, DNS_TYPE_NSAP)
    DNS_CHECK_TYPE(DNS_STR_TYPE_NSAP_PTR, DNS_TYPE_NSAP_PTR)
    DNS_CHECK_TYPE(DNS_STR_TYPE_SIG, DNS_TYPE_SIG)
    DNS_CHECK_TYPE(DNS_STR_TYPE_KEY, DNS_TYPE_KEY)
    DNS_CHECK_TYPE(DNS_STR_TYPE_PX, DNS_TYPE_PX)
    DNS_CHECK_TYPE(DNS_STR_TYPE_GPOS, DNS_TYPE_GPOS)
    DNS_CHECK_TYPE(DNS_STR_TYPE_AAAA, DNS_TYPE_AAAA)
    DNS_CHECK_TYPE(DNS_STR_TYPE_LOC, DNS_TYPE_LOC)
    DNS_CHECK_TYPE(DNS_STR_TYPE_NXT, DNS_TYPE_NXT)
    DNS_CHECK_TYPE(DNS_STR_TYPE_EID, DNS_TYPE_EID)
    DNS_CHECK_TYPE(DNS_STR_TYPE_NIMLOC, DNS_TYPE_NIMLOC)
    DNS_CHECK_TYPE(DNS_STR_TYPE_SRV, DNS_TYPE_SRV)
    DNS_CHECK_TYPE(DNS_STR_TYPE_ATMA, DNS_TYPE_ATMA)
    DNS_CHECK_TYPE(DNS_STR_TYPE_NAPTR, DNS_TYPE_NAPTR)
    DNS_CHECK_TYPE(DNS_STR_TYPE_KX, DNS_TYPE_KX)
    DNS_CHECK_TYPE(DNS_STR_TYPE_CERT, DNS_TYPE_CERT)
    DNS_CHECK_TYPE(DNS_STR_TYPE_A6, DNS_TYPE_A6)
    DNS_CHECK_TYPE(DNS_STR_TYPE_DNAME, DNS_TYPE_DNAME)
    DNS_CHECK_TYPE(DNS_STR_TYPE_SINK, DNS_TYPE_SINK)
    DNS_CHECK_TYPE(DNS_STR_TYPE_OPT, DNS_TYPE_OPT)
    DNS_CHECK_TYPE(DNS_STR_TYPE_APL, DNS_TYPE_APL)
    DNS_CHECK_TYPE(DNS_STR_TYPE_DS, DNS_TYPE_DS)
    DNS_CHECK_TYPE(DNS_STR_TYPE_SSHFP, DNS_TYPE_SSHFP)
    DNS_CHECK_TYPE(DNS_STR_TYPE_IPSECKEY, DNS_TYPE_IPSECKEY)
    DNS_CHECK_TYPE(DNS_STR_TYPE_RRSIG, DNS_TYPE_RRSIG)
    DNS_CHECK_TYPE(DNS_STR_TYPE_NSEC, DNS_TYPE_NSEC)
    DNS_CHECK_TYPE(DNS_STR_TYPE_DNSKEY, DNS_TYPE_DNSKEY)
    DNS_CHECK_TYPE(DNS_STR_TYPE_DHCID, DNS_TYPE_DHCID)
    DNS_CHECK_TYPE(DNS_STR_TYPE_NSEC3, DNS_TYPE_NSEC3)
    DNS_CHECK_TYPE(DNS_STR_TYPE_NSEC3PARAM, DNS_TYPE_NSEC3PARAM)
    DNS_CHECK_TYPE(DNS_STR_TYPE_TLSA, DNS_TYPE_TLSA)
    DNS_CHECK_TYPE(DNS_STR_TYPE_SMIMEA, DNS_TYPE_SMIMEA)
    DNS_CHECK_TYPE(DNS_STR_TYPE_HIP, DNS_TYPE_HIP)
    DNS_CHECK_TYPE(DNS_STR_TYPE_NINFO, DNS_TYPE_NINFO)
    DNS_CHECK_TYPE(DNS_STR_TYPE_RKEY, DNS_TYPE_RKEY)
    DNS_CHECK_TYPE(DNS_STR_TYPE_TALINK, DNS_TYPE_TALINK)
    DNS_CHECK_TYPE(DNS_STR_TYPE_CDS, DNS_TYPE_CDS)
    DNS_CHECK_TYPE(DNS_STR_TYPE_CDNSKEY, DNS_TYPE_CDNSKEY)
    DNS_CHECK_TYPE(DNS_STR_TYPE_OPENPGPKEY, DNS_TYPE_OPENPGPKEY)
    DNS_CHECK_TYPE(DNS_STR_TYPE_CSYNC, DNS_TYPE_CSYNC)
    DNS_CHECK_TYPE(DNS_STR_TYPE_ZONEMD, DNS_TYPE_ZONEMD)
    DNS_CHECK_TYPE(DNS_STR_TYPE_SVCB, DNS_TYPE_SVCB)
    DNS_CHECK_TYPE(DNS_STR_TYPE_HTTPS, DNS_TYPE_HTTPS)
    DNS_CHECK_TYPE(DNS_STR_TYPE_SPF, DNS_TYPE_SPF)
    DNS_CHECK_TYPE(DNS_STR_TYPE_UINFO, DNS_TYPE_UINFO)
    DNS_CHECK_TYPE(DNS_STR_TYPE_UID, DNS_TYPE_UID)
    DNS_CHECK_TYPE(DNS_STR_TYPE_GID, DNS_TYPE_GID)
    DNS_CHECK_TYPE(DNS_STR_TYPE_UNSPEC, DNS_TYPE_UNSPEC)
    DNS_CHECK_TYPE(DNS_STR_TYPE_NID, DNS_TYPE_NID)
    DNS_CHECK_TYPE(DNS_STR_TYPE_L32, DNS_TYPE_L32)
    DNS_CHECK_TYPE(DNS_STR_TYPE_L64, DNS_TYPE_L64)
    DNS_CHECK_TYPE(DNS_STR_TYPE_LP, DNS_TYPE_LP)
    DNS_CHECK_TYPE(DNS_STR_TYPE_EUI48, DNS_TYPE_EUI48)
    DNS_CHECK_TYPE(DNS_STR_TYPE_EUI64, DNS_TYPE_EUI64)
    DNS_CHECK_TYPE(DNS_STR_TYPE_TKEY, DNS_TYPE_TKEY)
    DNS_CHECK_TYPE(DNS_STR_TYPE_TSIG, DNS_TYPE_TSIG)
    DNS_CHECK_TYPE(DNS_STR_TYPE_IXFR, DNS_TYPE_IXFR)
    DNS_CHECK_TYPE(DNS_STR_TYPE_AXFR, DNS_TYPE_AXFR)
    DNS_CHECK_TYPE(DNS_STR_TYPE_MAILB, DNS_TYPE_MAILB)
    DNS_CHECK_TYPE(DNS_STR_TYPE_MAILA, DNS_TYPE_MAILA)
    DNS_CHECK_TYPE(DNS_STR_TYPE_URI, DNS_TYPE_URI)
    DNS_CHECK_TYPE(DNS_STR_TYPE_CAA, DNS_TYPE_CAA)
    DNS_CHECK_TYPE(DNS_STR_TYPE_AVC, DNS_TYPE_AVC)
    DNS_CHECK_TYPE(DNS_STR_TYPE_DOA, DNS_TYPE_DOA)
    DNS_CHECK_TYPE(DNS_STR_TYPE_AMTREPLAY, DNS_TYPE_AMTREPLAY)
    DNS_CHECK_TYPE(DNS_STR_TYPE_TA, DNS_TYPE_TA)
    DNS_CHECK_TYPE(DNS_STR_TYPE_DLV, DNS_TYPE_DLV)

finish:
    free(dns_type);
    return result;
}

#define DNS_CHECK_INT_TYPE(value, stdValue) \
    case (value):                           \
        return (stdValue);                  \
        break;

char* int_to_dns_type(uint16_t type)
{
    switch (type) {
        DNS_CHECK_INT_TYPE(DNS_TYPE_A, DNS_STR_TYPE_A)
        DNS_CHECK_INT_TYPE(DNS_TYPE_NS, DNS_STR_TYPE_NS)
        DNS_CHECK_INT_TYPE(DNS_TYPE_MD, DNS_STR_TYPE_MD)
        DNS_CHECK_INT_TYPE(DNS_TYPE_MF, DNS_STR_TYPE_MF)
        DNS_CHECK_INT_TYPE(DNS_TYPE_CNAME, DNS_STR_TYPE_CNAME)
        DNS_CHECK_INT_TYPE(DNS_TYPE_SOA, DNS_STR_TYPE_SOA)
        DNS_CHECK_INT_TYPE(DNS_TYPE_MB, DNS_STR_TYPE_MB)
        DNS_CHECK_INT_TYPE(DNS_TYPE_MG, DNS_STR_TYPE_MG)
        DNS_CHECK_INT_TYPE(DNS_TYPE_MR, DNS_STR_TYPE_MR)
        DNS_CHECK_INT_TYPE(DNS_TYPE_NULL, DNS_STR_TYPE_NULL)
        DNS_CHECK_INT_TYPE(DNS_TYPE_WKS, DNS_STR_TYPE_WKS)
        DNS_CHECK_INT_TYPE(DNS_TYPE_PTR, DNS_STR_TYPE_PTR)
        DNS_CHECK_INT_TYPE(DNS_TYPE_HINFO, DNS_STR_TYPE_HINFO)
        DNS_CHECK_INT_TYPE(DNS_TYPE_MINFO, DNS_STR_TYPE_MINFO)
        DNS_CHECK_INT_TYPE(DNS_TYPE_MX, DNS_STR_TYPE_MX)
        DNS_CHECK_INT_TYPE(DNS_TYPE_TXT, DNS_STR_TYPE_TXT)
        DNS_CHECK_INT_TYPE(DNS_TYPE_RP, DNS_STR_TYPE_RP)
        DNS_CHECK_INT_TYPE(DNS_TYPE_AFSDB, DNS_STR_TYPE_AFSDB)
        DNS_CHECK_INT_TYPE(DNS_TYPE_X25, DNS_STR_TYPE_X25)
        DNS_CHECK_INT_TYPE(DNS_TYPE_ISDN, DNS_STR_TYPE_ISDN)
        DNS_CHECK_INT_TYPE(DNS_TYPE_RT, DNS_STR_TYPE_RT)
        DNS_CHECK_INT_TYPE(DNS_TYPE_NSAP, DNS_STR_TYPE_NSAP)
        DNS_CHECK_INT_TYPE(DNS_TYPE_NSAP_PTR, DNS_STR_TYPE_NSAP_PTR)
        DNS_CHECK_INT_TYPE(DNS_TYPE_SIG, DNS_STR_TYPE_SIG)
        DNS_CHECK_INT_TYPE(DNS_TYPE_KEY, DNS_STR_TYPE_KEY)
        DNS_CHECK_INT_TYPE(DNS_TYPE_PX, DNS_STR_TYPE_PX)
        DNS_CHECK_INT_TYPE(DNS_TYPE_GPOS, DNS_STR_TYPE_GPOS)
        DNS_CHECK_INT_TYPE(DNS_TYPE_AAAA, DNS_STR_TYPE_AAAA)
        DNS_CHECK_INT_TYPE(DNS_TYPE_LOC, DNS_STR_TYPE_LOC)
        DNS_CHECK_INT_TYPE(DNS_TYPE_NXT, DNS_STR_TYPE_NXT)
        DNS_CHECK_INT_TYPE(DNS_TYPE_EID, DNS_STR_TYPE_EID)
        DNS_CHECK_INT_TYPE(DNS_TYPE_NIMLOC, DNS_STR_TYPE_NIMLOC)
        DNS_CHECK_INT_TYPE(DNS_TYPE_SRV, DNS_STR_TYPE_SRV)
        DNS_CHECK_INT_TYPE(DNS_TYPE_ATMA, DNS_STR_TYPE_ATMA)
        DNS_CHECK_INT_TYPE(DNS_TYPE_NAPTR, DNS_STR_TYPE_NAPTR)
        DNS_CHECK_INT_TYPE(DNS_TYPE_KX, DNS_STR_TYPE_KX)
        DNS_CHECK_INT_TYPE(DNS_TYPE_CERT, DNS_STR_TYPE_CERT)
        DNS_CHECK_INT_TYPE(DNS_TYPE_A6, DNS_STR_TYPE_A6)
        DNS_CHECK_INT_TYPE(DNS_TYPE_DNAME, DNS_STR_TYPE_DNAME)
        DNS_CHECK_INT_TYPE(DNS_TYPE_SINK, DNS_STR_TYPE_SINK)
        DNS_CHECK_INT_TYPE(DNS_TYPE_OPT, DNS_STR_TYPE_OPT)
        DNS_CHECK_INT_TYPE(DNS_TYPE_APL, DNS_STR_TYPE_APL)
        DNS_CHECK_INT_TYPE(DNS_TYPE_DS, DNS_STR_TYPE_DS)
        DNS_CHECK_INT_TYPE(DNS_TYPE_SSHFP, DNS_STR_TYPE_SSHFP)
        DNS_CHECK_INT_TYPE(DNS_TYPE_IPSECKEY, DNS_STR_TYPE_IPSECKEY)
        DNS_CHECK_INT_TYPE(DNS_TYPE_RRSIG, DNS_STR_TYPE_RRSIG)
        DNS_CHECK_INT_TYPE(DNS_TYPE_NSEC, DNS_STR_TYPE_NSEC)
        DNS_CHECK_INT_TYPE(DNS_TYPE_DNSKEY, DNS_STR_TYPE_DNSKEY)
        DNS_CHECK_INT_TYPE(DNS_TYPE_DHCID, DNS_STR_TYPE_DHCID)
        DNS_CHECK_INT_TYPE(DNS_TYPE_NSEC3, DNS_STR_TYPE_NSEC3)
        DNS_CHECK_INT_TYPE(DNS_TYPE_NSEC3PARAM, DNS_STR_TYPE_NSEC3PARAM)
        DNS_CHECK_INT_TYPE(DNS_TYPE_TLSA, DNS_STR_TYPE_TLSA)
        DNS_CHECK_INT_TYPE(DNS_TYPE_SMIMEA, DNS_STR_TYPE_SMIMEA)
        DNS_CHECK_INT_TYPE(DNS_TYPE_HIP, DNS_STR_TYPE_HIP)
        DNS_CHECK_INT_TYPE(DNS_TYPE_NINFO, DNS_STR_TYPE_NINFO)
        DNS_CHECK_INT_TYPE(DNS_TYPE_RKEY, DNS_STR_TYPE_RKEY)
        DNS_CHECK_INT_TYPE(DNS_TYPE_TALINK, DNS_STR_TYPE_TALINK)
        DNS_CHECK_INT_TYPE(DNS_TYPE_CDS, DNS_STR_TYPE_CDS)
        DNS_CHECK_INT_TYPE(DNS_TYPE_CDNSKEY, DNS_STR_TYPE_CDNSKEY)
        DNS_CHECK_INT_TYPE(DNS_TYPE_OPENPGPKEY, DNS_STR_TYPE_OPENPGPKEY)
        DNS_CHECK_INT_TYPE(DNS_TYPE_CSYNC, DNS_STR_TYPE_CSYNC)
        DNS_CHECK_INT_TYPE(DNS_TYPE_ZONEMD, DNS_STR_TYPE_ZONEMD)
        DNS_CHECK_INT_TYPE(DNS_TYPE_SVCB, DNS_STR_TYPE_SVCB)
        DNS_CHECK_INT_TYPE(DNS_TYPE_HTTPS, DNS_STR_TYPE_HTTPS)
        DNS_CHECK_INT_TYPE(DNS_TYPE_SPF, DNS_STR_TYPE_SPF)
        DNS_CHECK_INT_TYPE(DNS_TYPE_UINFO, DNS_STR_TYPE_UINFO)
        DNS_CHECK_INT_TYPE(DNS_TYPE_UID, DNS_STR_TYPE_UID)
        DNS_CHECK_INT_TYPE(DNS_TYPE_GID, DNS_STR_TYPE_GID)
        DNS_CHECK_INT_TYPE(DNS_TYPE_UNSPEC, DNS_STR_TYPE_UNSPEC)
        DNS_CHECK_INT_TYPE(DNS_TYPE_NID, DNS_STR_TYPE_NID)
        DNS_CHECK_INT_TYPE(DNS_TYPE_L32, DNS_STR_TYPE_L32)
        DNS_CHECK_INT_TYPE(DNS_TYPE_L64, DNS_STR_TYPE_L64)
        DNS_CHECK_INT_TYPE(DNS_TYPE_LP, DNS_STR_TYPE_LP)
        DNS_CHECK_INT_TYPE(DNS_TYPE_EUI48, DNS_STR_TYPE_EUI48)
        DNS_CHECK_INT_TYPE(DNS_TYPE_EUI64, DNS_STR_TYPE_EUI64)
        DNS_CHECK_INT_TYPE(DNS_TYPE_TKEY, DNS_STR_TYPE_TKEY)
        DNS_CHECK_INT_TYPE(DNS_TYPE_TSIG, DNS_STR_TYPE_TSIG)
        DNS_CHECK_INT_TYPE(DNS_TYPE_IXFR, DNS_STR_TYPE_IXFR)
        DNS_CHECK_INT_TYPE(DNS_TYPE_AXFR, DNS_STR_TYPE_AXFR)
        DNS_CHECK_INT_TYPE(DNS_TYPE_MAILB, DNS_STR_TYPE_MAILB)
        DNS_CHECK_INT_TYPE(DNS_TYPE_MAILA, DNS_STR_TYPE_MAILA)
        DNS_CHECK_INT_TYPE(DNS_TYPE_URI, DNS_STR_TYPE_URI)
        DNS_CHECK_INT_TYPE(DNS_TYPE_CAA, DNS_STR_TYPE_CAA)
        DNS_CHECK_INT_TYPE(DNS_TYPE_AVC, DNS_STR_TYPE_AVC)
        DNS_CHECK_INT_TYPE(DNS_TYPE_DOA, DNS_STR_TYPE_DOA)
        DNS_CHECK_INT_TYPE(DNS_TYPE_AMTREPLAY, DNS_STR_TYPE_AMTREPLAY)
        DNS_CHECK_INT_TYPE(DNS_TYPE_TA, DNS_STR_TYPE_TA)
        DNS_CHECK_INT_TYPE(DNS_TYPE_DLV, DNS_STR_TYPE_DLV)

    default:
        return "ERROR";
        break;
    }
}