name: build
on: [push]
jobs:
  alpine:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['3.16.2']
    container:
      image: alpine:${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up container
        run: |
          apk add \
            autoconf \
            automake \
            check-dev \
            gcc \
            libtool \
            make \
            musl-dev \
            pkgconfig \
            py3-dev \
            py3-pip \
            py3-wheel
      - name: build and install
        run: |
          autoreconf -i
          ./configure --enable-python --prefix=/usr
          make check
          make install
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['22.10']
    container:
      image: ubuntu:${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up container
        run: |
          apt update
          apt install -y \
            autoconf \
            automake \
            check \
            gcc \
            libtool \
            make \
            pkg-config \
            libpython3-dev \
            python3 \
            python3-pip \
            python3-wheel
      - name: build and install
        run: |
          autoreconf -i
          ./configure --enable-python --prefix=/usr
          make check
          make install