name: build
on: [push]
jobs:
  ubuntu:
    strategy:
      matrix:
        version: ['22.10']
      container:
        image: ubuntu:${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up container
        run: |
          apt update
          apt install -y \
            autoconf \
            automake \
            check \
            gcc \
            libtool \
            make \
            pkg-config \
            libpython3-dev \
            python3 \
            python3-pip \
            python3-wheel
      - name: build and install
        run: |
          autoreconf -i
          ./configure --enable-python --prefix=/usr
          make check
          make install