name: build
on: [push]
jobs:
  alpine:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['3.16.3', '3.17.0']
        cc: ['clang', 'gcc']
    container:
      image: alpine:${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up container
        run: |
          apk add \
            autoconf \
            automake \
            check-dev \
            clang \
            gcc \
            json-c-dev \
            libevent-dev \
            libtool \
            make \
            musl-dev \
            nghttp2-dev \
            openssl-dev \
            pkgconfig \
            python3-dev \
            py3-pip \
            py3-wheel
      - name: build and install
        run: |
          autoreconf -i
          CC=${{ matrix.cc }} ./configure --enable-python --prefix=/usr
          make check
          make install
  fedora:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['38']
        cc: ['clang', 'gcc']
    container:
      image: fedora:${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up container
        run: |
          dnf install -y \
            autoconf \
            automake \
            check-devel \
            clang \
            gcc \
            json-c-devel \
            libevent-devel \
            libnghttp2-devel \
            libtool \
            make \
            openssl-devel \
            pkgconfig \
            python3-devel \
            python3-pip \
            python3-wheel
      - name: build and install
        run: |
          autoreconf -i
          CC=${{ matrix.cc }} ./configure --enable-python --prefix=/usr
          make check
          make install
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['22.10']
        cc: ['clang', 'gcc']
    container:
      image: ubuntu:${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up container
        run: |
          apt update
          apt install -y \
            autoconf \
            automake \
            check \
            clang \
            gcc \
            libevent-dev \
            libjson-c-dev \
            libnghttp2-dev \
            libssl-dev \
            libtool \
            make \
            pkg-config \
            libpython3-dev \
            python3 \
            python3-pip \
            python3-wheel
      - name: build and install
        run: |
          autoreconf -i
          CC=${{ matrix.cc }} ./configure --enable-python --prefix=/usr
          make check
          make install