name: cppcheck
on: [push]
jobs:
  alpine:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.17.3
    steps:
      - uses: actions/checkout@v2
      - name: Set up container
        run: |
          apk add \
            autoconf \
            automake \
            check-dev \
            cppcheck \
            gcc \
            json-c-dev \
            libevent-dev \
            libtool \
            make \
            musl-dev \
            nghttp2-dev \
            openssl-dev \
            pkgconfig
      - name: make cppcheck
        run: |
          autoreconf -i
          ./configure
          make cppcheck